[package]
name = "database"
version = "0.1.0"
authors = ["Mark Rousskov <mark.simulacrum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#welcome database
hashbrown = { version = "0.7", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.23", features = ["bundled"] }
tokio-postgres = { version = "0.5.4", features = ["with-serde_json-1", "with-chrono-0_4"] }
anyhow = "1"
async-trait = "0.1"
tokio = { version = "0.2.21", features = ["sync", "macros"] }
snap = "1"
intern = { path = "../intern" }
chrono = "0.4"
reqwest = { version = "0.10.5", features = ["blocking"] }
postgres-native-tls = "0.3"
native-tls = "0.2"
lazy_static = "1"
env_logger = "0.7"
futures = "0.3.5"
log = "0.4"
